//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisite
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string Brand { get; set; }
        public string Number { get; set; }
        public string VehicleDescription { get; set; }
        public string VehicleType { get; set; }
        public string Description { get; set; }
        public int StatusId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Count { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
    }
}
